# INSERT INTO course
# (id, name, description, instructor_id, duration, price, learner_count, review_count, stars_count, image_url, category_id) VALUES
#                                                                                                                               (1, 'Java Programming Basics', 'Learn Java from scratch including OOP concepts.', 1, '10 hours', 49.99, 1500, 200, 900, 'https://example.com/images/java_basics.png', 1),
#                                                                                                                               (2, 'Full Stack Web Development', 'Become a full-stack developer using React and Node.js.', 2, '40 hours', 199.99, 2300, 320, 1100, 'https://example.com/images/fullstack_webdev.png', 2),
#                                                                                                                               (3, 'Introduction to Machine Learning', 'Learn ML algorithms and implement projects.', 3, '25 hours', 149.99, 1800, 280, 950, 'https://example.com/images/ml_intro.png', 3),
#                                                                                                                               (4, 'UI/UX Design Fundamentals', 'Design beautiful and user-friendly interfaces.', 4, '15 hours', 99.99, 800, 100, 450, 'https://example.com/images/uiux_design.png', 4),
#                                                                                                                               (5, 'Digital Marketing 101', 'Master social media marketing, SEO, and more.', 5, '12 hours', 59.99, 1200, 150, 600, 'https://example.com/images/digital_marketing.png', 5),
#                                                                                                                               (6, 'Entrepreneurship Essentials', 'Start and manage your own business successfully.', 6, '20 hours', 79.99, 900, 110, 480, 'https://example.com/images/entrepreneurship.png', 6),
#                                                                                                                               (7, 'Spanish for Beginners', 'Learn basic Spanish for everyday conversation.', 7, '8 hours', 29.99, 1600, 210, 850, 'https://example.com/images/spanish_beginners.png', 7),
#                                                                                                                               (8, 'Photography Masterclass', 'Master DSLR photography and editing.', 8, '18 hours', 89.99, 1100, 130, 550, 'https://example.com/images/photography_masterclass.png', 8),
#                                                                                                                               (9, 'Guitar for Beginners', 'Learn guitar chords and songs from scratch.', 9, '10 hours', 49.99, 1400, 170, 720, 'https://example.com/images/guitar_beginners.png', 9),
#                                                                                                                               (10, 'Nutrition and Fitness Basics', 'Improve your health with diet and exercise.', 10, '12 hours', 39.99, 1300, 160, 680, 'https://example.com/images/health_fitness.png', 10);

# INSERT INTO course (id, name, description, instructor_id, duration, price, learner_count, review_count, stars_count, image_url, category_id) VALUES
#                                                                                                                                                  (1, 'Java Fundamentals', 'Learn the basics of Java programming.', 102, '6 weeks', 99.99, 100, 20, 85, 'https://example.com/images/java.jpg', 1),
#                                                                                                                                                  (2, 'Spring Boot Deep Dive', 'Comprehensive guide to building REST APIs using Spring Boot.', 103, '8 weeks', 149.99, 75, 15, 70, 'https://example.com/images/springboot.jpg', 2),
#                                                                                                                                                  (3, 'Python for Beginners', 'Get started with Python from scratch.', 104, '5 weeks', 89.99, 150, 30, 120, 'https://example.com/images/python.jpg', 1),
#                                                                                                                                                  (4, 'Web Development with React', 'Build dynamic web apps using React.js.', 105, '7 weeks', 129.99, 90, 18, 95, 'https://example.com/images/react.jpg', 3),
#                                                             x                                                                                     (5, 'Machine Learning Basics', 'Introductory course to ML and AI concepts.', 106, '10 weeks', 199.99, 60, 25, 110, 'https://example.com/images/ml.jpg', 2),
#                                                                                                                                                  (6, 'Data Structures in C++', 'Master data structures with practical C++ examples.', 107, '6 weeks', 109.99, 80, 12, 65, 'https://example.com/images/cpp.jpg', 1),
#                                                                                                                                                  (7, 'DevOps with Docker & Kubernetes', 'Learn CI/CD, Docker and K8s basics.', 108, '8 weeks', 159.99, 55, 10, 75, 'https://example.com/images/devops.jpg', 3),
#                                                                                                                                                  (8, 'Android App Development', 'Build Android apps using Kotlin.', 109, '9 weeks', 139.99, 70, 14, 90, 'https://example.com/images/android.jpg', 2),
#                                                                                                                                                  (9, 'Frontend Mastery', 'HTML, CSS and JavaScript for modern web design.', 110, '6 weeks', 79.99, 120, 28, 100, 'https://example.com/images/frontend.jpg', 3),
#                                                                                                                                                  (10, 'SQL and Database Design', 'Learn to design and query relational databases.', 111, '4 weeks', 69.99, 110, 20, 88, 'https://example.com/images/sql.jpg', 1);
